### ISSUE TITLE
conflicting lifecycle mapping issue

### ISSUE THREAD

**Issue by nik-jo** [LorenzoBettini/xtext-maven-plugin-example#2]
When I import this project I get the error of conflicting life cycle mapping at 	<packaging>eclipse-plugin</packaging>

Conflicting lifecycle mapping metadata (project packaging type="eclipse-plugin"): Mapping defined in 'org.eclipse.m2e.pde.connector_2.1.500.20231119-0901 [318]' and 'org.sonatype.tycho.m2e_0.10.0.20220926-1324 [890]'. To enable full functionality, remove the conflicting mapping and run Maven->Update Project Configuration.

**Comment by LorenzoBettini** [comment]
I don't think the error is related to this project: such connectors are not listed in the poms, are they?

**Comment by nik-jo** [comment]
Yes, I think you're right - apologies.  The org.eclipse.m2e is listed in the pom.  Not sure where the org.sonatype.tycho.m2e conflict is coming from.  I thought maybe it was something that was used in tycho maven.
